-- Tables
CREATE TABLE configuration.public_holiday_fixed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    month SMALLINT NOT NULL,
    day SMALLINT NOT NULL,
    label VARCHAR(100),
    PRIMARY KEY (id)
);

CREATE TABLE configuration.public_holiday_variable (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    date DATE NOT NULL,
    label VARCHAR(100),
    PRIMARY KEY (id)
);

-- Constraints
ALTER TABLE configuration.public_holiday_fixed
    ADD CONSTRAINT chk_holiday_month CHECK (month BETWEEN 1 AND 12),
    ADD CONSTRAINT chk_holiday_day CHECK (day BETWEEN 1 AND 31);

ALTER TABLE configuration.public_holiday_fixed
    ADD CONSTRAINT uq_public_holiday_fixed UNIQUE (month, day);
ALTER TABLE configuration.public_holiday_variable
    ADD CONSTRAINT uq_public_holiday_variable UNIQUE (date);

-- Permissions
GRANT ALL ON ALL TABLES IN SCHEMA configuration TO jinji_adm;