-- Table
CREATE TABLE business.notification (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL,
    read BOOLEAN NOT NULL DEFAULT false,
    message VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY(id)
);

-- Constraint
ALTER TABLE business.notification
    ADD CONSTRAINT fk_notification_user_id FOREIGN KEY (user_id) REFERENCES business.users(id);

-- Permissions
GRANT ALL ON ALL TABLES IN SCHEMA business TO jinji_adm;
