-- Tables
CREATE TABLE configuration.company (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    identification_number VARCHAR(50),
    PRIMARY KEY(id)
);

CREATE TABLE configuration.department (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(100),
    PRIMARY KEY(id)
);

CREATE TABLE business.employee (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    employee_number VARCHAR(12) NOT NULL,
    surname VARCHAR(255),
    first_name VARCHAR(255),
    email VARCHAR(255),
    phone_number VARCHAR(20),
    seniority_date DATE,
    department_id BIGINT,
    PRIMARY KEY(id)
);

CREATE TABLE business.team (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(100),
    manager BIGINT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE business.employee_team (
    team_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    PRIMARY KEY (team_id, employee_id)
);

CREATE TABLE business.users (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT false,
    employee_id BIGINT,
    PRIMARY KEY(id)
);

CREATE TABLE business.role (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(10),
    label VARCHAR(50),
    PRIMARY KEY(id)
);

CREATE TABLE business.users_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

-- Constraints
ALTER TABLE business.users ADD CONSTRAINT uk_users_username UNIQUE (username);
ALTER TABLE business.employee ADD CONSTRAINT uk_employee_email UNIQUE (email);

ALTER TABLE business.employee ADD CONSTRAINT fk_department_id FOREIGN KEY (department_id) REFERENCES configuration.department(id);
ALTER TABLE business.team ADD CONSTRAINT fk_manager FOREIGN KEY (manager) REFERENCES business.employee(id);
ALTER TABLE business.employee_team ADD CONSTRAINT fk_employee_id FOREIGN KEY (employee_id) REFERENCES business.employee(id) ON DELETE CASCADE;
ALTER TABLE business.employee_team ADD CONSTRAINT fk_team_id FOREIGN KEY (team_id) REFERENCES business.team(id) ON DELETE CASCADE;
ALTER TABLE business.users ADD CONSTRAINT fk_employee_id FOREIGN KEY (employee_id) REFERENCES business.employee(id);
ALTER TABLE business.users_role ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES business.users(id);
ALTER TABLE business.users_role ADD CONSTRAINT fk_role_id FOREIGN KEY (role_id) REFERENCES business.role(id);

-- Permissions
GRANT ALL ON ALL TABLES IN SCHEMA configuration TO jinji_adm;
GRANT ALL ON ALL TABLES IN SCHEMA business TO jinji_adm;
