-- Types
CREATE TYPE period_type AS ENUM ('AM', 'PM');

-- Tables
CREATE TABLE business.leave_type (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(20) NOT NULL,
    label VARCHAR(100) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE business.leave_request (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    start_period period_type NOT NULL DEFAULT 'AM',
    end_period period_type NOT NULL DEFAULT 'PM',
    status VARCHAR(9) NOT NULL DEFAULT 'PENDING',
    employee_comment VARCHAR(255),
    employee_id BIGINT NOT NULL,
    leave_type_id BIGINT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE business.leave_request_review (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    reviewer_role VARCHAR(10) NOT NULL,
    decision VARCHAR(8) NOT NULL,
    comment VARCHAR(255),
    reviewed_at TIMESTAMP NOT NULL,
    leave_request_id BIGINT NOT NULL,
    reviewed_by BIGINT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE business.leave (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    start_period period_type NOT NULL DEFAULT 'AM',
    end_period period_type NOT NULL DEFAULT 'PM',
    status VARCHAR(9) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL,
    created_by BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    leave_request_id BIGINT,
    leave_type_id BIGINT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE business.leave_balance (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(100) NOT NULL,
    acquisition_start_date DATE NOT NULL,
    acquisition_end_date DATE NOT NULL,
    acquired_days INTEGER NOT NULL,
    taken_days INTEGER NOT NULL DEFAULT 0,
    employee_id BIGINT NOT NULL,
    leave_type_id BIGINT NOT NULL,
    PRIMARY KEY(id)
);

-- Constraints
ALTER TABLE business.leave_type ADD CONSTRAINT uk_leave_type_code UNIQUE (code);

ALTER TABLE business.leave_request
    ADD CONSTRAINT fk_leave_request_leave_type_id FOREIGN KEY (leave_type_id) REFERENCES business.leave_type(id),
    ADD CONSTRAINT fk_leave_request_employee_id FOREIGN KEY (employee_id) REFERENCES business.employee(id);
ALTER TABLE business.leave_request_review
    ADD CONSTRAINT fk_leave_request_id FOREIGN KEY (leave_request_id) REFERENCES business.leave_request(id),
    ADD CONSTRAINT fk_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES business.employee(id);
ALTER TABLE business.leave
    ADD CONSTRAINT fk_leave_leave_type_id FOREIGN KEY (leave_type_id) REFERENCES business.leave_type(id),
    ADD CONSTRAINT fk_leave_employee_id FOREIGN KEY (employee_id) REFERENCES business.employee(id),
    ADD CONSTRAINT fk_leave_leave_request_id FOREIGN KEY (leave_request_id) REFERENCES business.leave_request(id),
    ADD CONSTRAINT fk_created_by FOREIGN KEY (created_by) REFERENCES business.employee(id);
ALTER TABLE business.leave_balance
    ADD CONSTRAINT fk_leave_balance_leave_type_id FOREIGN KEY (leave_type_id) REFERENCES business.leave_type(id),
    ADD CONSTRAINT fk_leave_balance_employee_id FOREIGN KEY (employee_id) REFERENCES business.employee(id);

ALTER TABLE business.leave_request ADD CONSTRAINT chk_leave_request_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'));
ALTER TABLE business.leave_request_review
    ADD CONSTRAINT chk_leave_request_review_reviewer_role CHECK (reviewer_role IN ('HR', 'MANAGER')),
    ADD CONSTRAINT chk_leave_request_review_decision CHECK (decision IN ('APPROVED', 'REJECTED'));
ALTER TABLE business.leave ADD CONSTRAINT chk_leave_status CHECK (status IN ('ACTIVE', 'CANCELLED'));
ALTER TABLE business.leave_balance
    ADD CONSTRAINT chk_leave_balance_acquired_days_positive CHECK (acquired_days >= 0),
    ADD CONSTRAINT chk_leave_balance_taken_days_positive CHECK (taken_days >= 0);

-- Permissions
GRANT ALL ON ALL TABLES IN SCHEMA business TO jinji_adm;