-- Tables
CREATE TABLE configuration.hr_policy (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    leave_validation VARCHAR(50) NOT NULL,
    allow_unpaid_leave BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY(id)
);

-- Constraints
ALTER TABLE configuration.hr_policy
    ADD CONSTRAINT chk_leave_validation CHECK (leave_validation IN ('MANAGER_ONLY', 'MANAGER_THEN_HR'));

CREATE UNIQUE INDEX one_hr_policy_only
    ON configuration.hr_policy ((true));

-- Permissions
GRANT ALL ON ALL TABLES IN SCHEMA configuration TO jinji_adm;