spring.application.name=jinji

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

secret_jwt=V9gU8qMpDFxs6a4Bixvbtp5aE32unzWKEN8rsdCtUpm

spring.jpa.show-sql=true

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver