spring.application.name=jinji

spring.datasource.url=jdbc:postgresql://localhost:5432/jinji_db
spring.datasource.username=SPRING_DATASOURCE_USERNAME
spring.datasource.password=SPRING_DATASOURCE_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

spring.jpa.show-sql=true
