spring.application.name=jinji

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

secret_jwt=V9gU8qMpDFxs6a4Bixvbtp5aE32unzWKEN8rsdCtUpm

spring.jpa.show-sql=true

logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG